version: '3.7'
services:
  db:
    image: mariadb:10.5.8
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aneeq
      MYSQL_DATABASE: wp
      MYSQL_USER: root
      MYSQL_PASSWORD: Aneeq
    volumes:
      - ./mysql-data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Aneeq
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./wordpress-data:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Aneeq
      MYSQL_USER: root
      MYSQL_PASSWORD: Aneeq
    ports:
      - "8080:80"
    restart: always
